name: "Deploy to Azure"
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: "npm install, build"
        run: |
          npm install
          gatsby build

      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
